### ISSUE TITLE
Xbox Interactivity Button mappings are not ideal

### ISSUE THREAD

**Issue by hyperionteam-msft** [mixer/cdk-std#21]
While minigolf has worked around it, interactive apps will probably want access to as many buttons as possible. Perhaps the Xbox button can be leveraged for toggling interactive on/off.

Interactive apps currently on xbox can't use these gamepad buttons:
 - Y because of chat
 - B because it exits interactivity
 - A due to the issue below

A button issue:
When an Xbox user presses A on the "PRESS HERE TO INTERACT" button, the interactive html code captures that press using the [Gamepad](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/getGamepads). This event should be eaten before interactivity boots up.

**Comment by AechDub** [comment]
Sure.

Once interactive is open, your input is captured.  We currently provide an API to disable B exiting.  

If you want to disable B from exiting, you have a couple options.  You can either prevent in a one off, or prevent all for the session.  Take a look at the methods here: https://github.com/mixer/cdk-std/blob/503f7a1e122099a0352fd90b506a5e662e453431/src/bundle/navigation.ts#L65

A button wasn't previously an issue.  I'll take a look at that as well as the Y accelerator and ensure interactive is handling as we intend.
